PrivateKey: "1234567890"
Network: "testnet" # mainnet or testnet
RpcUrl: "https://mempool.space/testnet/api" # https://blockstream.info/testnet/api https://mempool.space/api https://mempool.space/testnet/api
FeePerByte: 5000
UtxoAmount: 1000
Etching:
  Rune: "RUNESSSSTUDYA"
  Symbol: "s"
  Premine: 1000000
  Amount: 1000
  Cap: 20000
#  Divisibility: 0
#  HeightStart: 0
#  HeightEnd: 0
#  HeightOffsetStart: 0
#  HeightOffsetEnd: 0
Mint:
  RuneId: "2584609:149"